### ISSUE TITLE
Add `is_geographic` or `is_projected` boolean property to meshkernel instance

### ISSUE THREAD

**Issue by veenstrajelmer** [Deltares/MeshKernelPy#108]
**Is your feature request related to a problem? Please describe.**
Quick question. When we want to save a meshkernel instance as a netcdf file, it is good to add "projection_x_coordinate" or "longitude" and other attributes. For this we need to know whether the meshkernel instance is projected/cartesian or spherical. Whether it is spherical or spherical accurate is irrelevant in this case, since the attributes would be the same. Maybe it is also useful to add a crs (coordinate reference system) to the meshkernel instance, but that might be out of the scope of meshkernel.

**Describe the solution you'd like**
I would like to avoid checking on `mk.get_projection()==meshkernel.ProjectionType.CARTESIAN` in several packages (dfm_tools, xugrid, hydromt, hydrolib-core and maybe in the future external packages also). Is there a boolean property of the meshkernel instance that provides this information? If not, could it be created?

For instance, when converting a meshkernel instance to xugrid.UgridDataset (xugrid.Ugrid2d) with xugrid.Ugrid2d.from_meshkernel() we need to know it:
https://github.com/Deltares/xugrid/blob/a021f190bc35dae4b325a11569f9d87d600bc9be/xugrid/ugrid/ugrid2d.py#L193

**Comment by ahmad-el-sayed** [comment]
The suggested solution does not make sense because more than 2 projection types are possible in the backend. Currently 2 are fully supported in MKPy for the time being.  What you can do is write a small function that does that:
```
def projection_is_cartesian(projection_type: ProjectionType):
  return projection_type == meshkernel.ProjectionType.CARTESIAN
``` 
Then use it as follows: `if(projection_is_cartesian(mk.get_projection())): ...`
