### ISSUE TITLE
Add API to get mesh edge lengths (and others)

### ISSUE THREAD

**Issue by veenstrajelmer** [Deltares/MeshKernelPy#152]
To support easy visualisation of mesh properties. The current exposed properties are these:
![image](https://github.com/Deltares/MeshKernelPy/assets/60435591/066efc84-bd2a-4579-9705-6da7a16c7495)

Properties:
- edge length
- cell area
- maybe more

In meters, also in case of a spherical grid.

Also: there is a `mk.mesh2d_delete_small_flow_edges_and_small_triangles()` available, but this is a combination of two actions and it is not possible to check if it is needed or not. Check DCSM workflow for more. Interacter defaults: small-links=0.1 (which means 0.1*sqrt(baL+baR)), small-triangles=0.2 (triangle removed if triaarea < average adjacent areas). Latter is often not used.

**Comment by lucacarniato** [comment]
also in case of spherical grid

**Comment by veenstrajelmer** [comment]
Implemented in https://github.com/Deltares/MeshKernel/pull/368
