### ISSUE TITLE
OSError: Unsupported operating system: Darwin

### ISSUE THREAD

**Issue by angelitora** [Deltares/MeshKernelPy#48]
**Describe the bug**
I understand it is not in the list of OS but trying to install this on my mac OSX Darwin is not working and it used to work on my previous mac. Do you have any suggestion for this issue?

**To Reproduce**
I have tried several pip actions: 
pip install meshkernel
pip install hydrolib-core
pip install dfm_tools

They all produce the same error:
        File "<string>", line 222, in <module>
        File "<string>", line 70, in get_library_name
      OSError: Unsupported operating system: Darwin
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

**Expected behavior**
Expected a smooth installation

**Screenshots**
NA

**Version info (please complete the following information):**
 - OS: macOS Big Sur 
 - Version 11.3.1

**Additional context**
NA

**Comment by ahmad-el-sayed** [comment]
Hi @angelitora. Support for macOS was temporarily disabled. Its workflow is now automated.  This is part of the upcoming release, v2.1.0.
You can find the wheel on this [page](https://github.com/Deltares/MeshKernelPy/actions/runs/5331393538) for example under `Artifacts`.  `meshkernel-macos-latest-Release ` is a zip file that contains the wheel.  
Please let us know if anything does not work as expected.

**Comment by veenstrajelmer** [comment]
@angelitora the current meshkernel>=4 supports macos again for two different architectures.
