### ISSUE TITLE
Adding edge_faces to MeshKernel().mesh2d_get()

### ISSUE THREAD

**Issue by RBTV1** [Deltares/MeshKernelPy#82]
When working with the output of the MeshKernel generator, it would be very useful to obtain further information on the connectivity of the faces. 
This would result in a matrix (2, edge_faces), where edge_faces is the number of edges that connect neighbouring faces, and in which each entry is given by the id of two neighbouring faces. Boundary faces should also have some sort of indication, such as assigning ghost cells with a value -1.

**Comment by Huite** [comment]
Not sure if it's helpful, but I've implemented these in xugrid as well: https://deltares.github.io/xugrid/api.html#ugrid2d-topology

You can create the xugrid objects from meshkernel objects directly:
https://deltares.github.io/xugrid/api/xugrid.Ugrid2d.from_meshkernel.html

Of course it requires installing an additional package. If that's undesirable, you can also derive them yourself, most of the logic can be found here: https://github.com/Deltares/xugrid/blob/main/xugrid/ugrid/connectivity.py
(And only requires numpy and scipy)

**Comment by lucacarniato** [comment]
I think it will be beneficial to have the edge_faces and face_edges as meshkernel output to ensure consistent indexing of the faces, also for xuugrid.

**Comment by lucacarniato** [comment]
this has been solved in GRIDEDIT-627
